config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  get 'calendar', to: 'calendar#show_calendar', as: 'calendar'
  resources :working_time_records, only: [:create, :index, :destroy, :update] do
    collection do
      post 'start'
      post 'end'
    end
  end

  resources :categories, only: [:create, :index, :destroy, :update] do
  end

  resources :users, only: [:show, :update] do 
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :working_time_records
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :working_time_records
  has_many :categories

  after_create :add_default_categories

  def add_default_categories
    Category.create!(
      user: self,
      category_name: "No category"
    )
  end


end

app/models/working_time_record.rb
class WorkingTimeRecord < ApplicationRecord
    belongs_to :user
    belongs_to :category

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  before_action :authenticate_user!

  def show_calendar
    @categories = current_user.categories

    if params['category_id'].nil? || params['category_id'].empty?
      @records = current_user.working_time_records
    else 
      @records = current_user.working_time_records.where(category_id: params['category_id'])
    end


  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :authenticate_user!

    def index
        @categories = current_user.categories
    end

    def create
        c = Category.new(category_params)
        c.user = current_user
        c.save!
    
        redirect_to categories_path
    end

    def destroy
        Category.destroy(params[:id])
        redirect_to categories_path
    end

    def update
        @category = Category.find(params[:id])
        @category.update(category_params)

        redirect_to categories_path
    end

    private
    def category_params
      params.require(:category).permit(:category_name)
    end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to user_path
  end

  def show
    @user = current_user
  end

  private
  def user_params
    params.require(:user).permit(:salary, :hours_number, :hours_by_month)
  end
end

app/controllers/working_time_records_controller.rb
class WorkingTimeRecordsController < ApplicationController
  before_action :authenticate_user!


  def index
    @working_time_records_all = current_user.working_time_records
    @working_time_records = @working_time_records_all.order(start_time: :desc).paginate(:page => params[:page], :per_page => 10)
    @today_time = @working_time_records_all.where(date: Date.today).sum{|a| a.end_time - a.start_time}
    @week_time = @working_time_records_all.select{|r| r.date <= Date.today && r.date >= Date.today.beginning_of_week}.sum{|a| a.end_time - a.start_time}
    @month_time = @working_time_records_all.select{|r| r.date <= Date.today && r.date >= Date.today.beginning_of_month}.sum{|a| a.end_time - a.start_time}
  end

  def create
    begin
      o = WorkingTimeRecord.new(adding_record_params)
      o.user = current_user
      o.save!
    rescue => e
      flash[:danger] = I18n.t('working_time_records.save_failure')
    end

    redirect_to working_time_records_path
  end

  def update 
    begin
      @working_time_records = WorkingTimeRecord.find(params[:id])
      @working_time_records.update!(record_params)
    rescue => e
      flash[:danger] = I18n.t('working_time_records.save_failure')
    end
    redirect_to working_time_records_path  
  end

  def destroy
    WorkingTimeRecord.destroy(params[:id])
    redirect_to working_time_records_path
  end

  def start 
    start_time = Time.now
    w = WorkingTimeRecord.new(date: Date.today, start_time: start_time, end_time: start_time, user: current_user, category: current_user.categories.where(category_name: "No category").first)
    w.save!
    redirect_to working_time_records_path
  end

  def end  
    end_time = Time.now
    w = current_user.working_time_records.last
    w.end_time = end_time
    w.save!
    redirect_to working_time_records_path
  end

  private

  def record_params
    params.require(:working_time_record).permit(:start_time, :end_time, :category_id)  
  end

  def adding_record_params
    a = params.require(:working_time_record).permit(:date, :start_time, :end_time, :category_id)
    a[:start_time] = a[:date] + ' ' + a[:start_time]
    a[:end_time] = a[:date] + ' ' + a[:end_time]
    a
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/working_time_records_helper.rb
module WorkingTimeRecordsHelper
end

app/views/calendar/show_calendar.html.slim
form action="calendar" method="get" enctype="multipart/form-data"
  .row.horizontal-form
    .col-md-4
      .form-group
        = label_tag 'category_id'
          = I18n.t('working_time_records.category')
        = select_tag :category_id, options_from_collection_for_select(@categories, "id", "category_name"), class: 'form-control',  value: params['category_id'].to_s

    .col-md-2
      .form-group
        button.btn.custom-btn.btn-block type="submit"
          = I18n.t('submit')



= month_calendar events: @records do |date, records| 
  = date.day
  - records.group_by{|o| o.date}.each do |date, records| 
    .show_time
      - time = records.sum{|a| a.end_time - a.start_time}
      - diff = TimeDifference.between(Time.now, Time.now + time).in_general
      = diff[:hours].to_s + ':' + diff[:minutes].to_s.rjust(2, '0') + ':' + diff[:seconds].to_s.rjust(2, '0')
    

app/views/categories/_add_category.html.slim
= form_for :category, url: categories_path, turboboost: true, method: :post  do |f|
  .modal.fade#add_category tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('categories.add_category')
        .modal-body
          .row
            .col-md-12
              .form-group
                = f.label :category_name, I18n.t('categories.category_name')
                = f.text_field :category_name, class: 'form-control'
        
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/categories/_edit_form.html.slim
= form_for category, url: category_path(category),  turboboost: true, method: :patch  do |f|
  .modal.fade id="category_edit_#{category.id}" tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('categories.edit_category')
        .modal-body
          .row
            .col-md-12
              .form-group
                = f.label :category_name, I18n.t('categories.category_name')
                = f.text_field :category_name, class: 'form-control' 
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/categories/_edit_forms.html.slim
- @categories.each do |category|
  = render partial: 'edit_form', locals: {category: category}

app/views/categories/index.html.slim
.panel.panel-default
  .panel-heading
    = I18n.t('categories.index')
    .btn-group.pull-right
      button.btn.btn-xs data-toggle="modal" data-target="#add_category" type="button"
        span.glyphicon.glyphicon-plus
  .panel-body
    table.table.table-hover
      thead
        tr
          th width="90%" = I18n.t('categories.category_name') 
          th width="10%"
      tbody 
      - @categories.each do |category|
          tr 
            td 
              = category.category_name
            td 
              - unless category.category_name == "No category"
                .btn-group.pull-right
                  button.btn.btn-xs.btn-primary data-toggle="modal" data-target="#category_edit_#{category.id}"
                    span.glyphicon.glyphicon-pencil
                  =link_to category_path(category), class: 'btn btn-xs btn-primary', method: :delete, data: {confirm: I18n.t('categories.delete_confirmation_message')}
                    span.glyphicon.glyphicon-remove
= render "add_category"
= render "edit_forms"

app/views/home/_header.html.slim
nav.navbar.navbar-default.navbar-static-top role="navigation" 
  .container-fluid
    a.navbar-brand 
      span.glyphicon.glyphicon-time
      = I18n.t('application_name')
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        - if user_signed_in?
          li= active_link_to I18n.t('working_time_records.index'), working_time_records_path
          li= active_link_to I18n.t('calendar.index'), calendar_path
          li= active_link_to I18n.t('categories.index'), categories_path
          li= active_link_to I18n.t('user.show'), user_path(current_user)
          - unless current_user.email == 'demo@example.com'
            li= active_link_to I18n.t('user.edit'), edit_user_registration_path
          li= active_link_to I18n.t('user.logout'), destroy_user_session_path, method: :delete
        - else
          li= active_link_to I18n.t('user.registration'), new_user_registration_path
          li= active_link_to I18n.t('user.login'), user_session_path
          /li= active_link_to I18n.t('demo'), demo_version_path
      ul.nav.navbar-nav.pull-right
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
            span.glyphicon.glyphicon-globe
            span.caret
          /ul.dropdown-menu.dropdown-menu-right
            li 
              = link_to params.permit(:locale, :user_id).merge({:locale => :pl}), :wrap_tag => :li
                span = image_tag("pl.jpg", :alt => "pl", style: "border: 1px solid black" )
                span = " Polski"
            li 
              = link_to params.permit(:locale, :user_id).merge({:locale => :en}), :wrap_tag => :li
                span = image_tag("en.jpg", :alt => "en", style: "border: 1px solid black")
                span = " English"
        

app/views/home/index.html.slim
h1
    | Hello world

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title = I18n.t('welcome.web_title')
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    = render 'home/header'
    .container
      - flash.each do |name, msg|
        .alert.alert-info.alert-dismissable
          button type="button" class="close" data-dismiss="alert"
            | &times;
          = msg
      = yield
      =javascript_tag "window.locale = #{I18n.locale.to_s.inspect};"

app/views/users/show.html.slim
h2 = I18n.t('user.change_data')
= form_for(@user, url: user_path(@user), html: { method: :patch }) do |f|
  .panel.panel-default
    .panel-body
      .row
        .col-md-4
          .form-group
            = f.label :salary, I18n.t('user.salary')
            = f.text_field :salary, autocomplete: "off", class: 'form-control'
        .col-md-4
          .form-group
            = f.label :hours_number, I18n.t('user.hours_number')
            = f.text_field :hours_number, autocomplete: "off", class: 'form-control'
        .col-md-4
          .form-group
            = f.label :hours_by_month, I18n.t('user.hours_by_month')
            = f.text_field :hours_by_month, autocomplete: "off", class: 'form-control'


    .panel-footer
      .row
        .col-md-12
          .pull-right
            button.btn.custom-btn type="submit" 
              = I18n.t('user.save')
    

app/views/working_time_records/_add_record.html.slim
= form_for :working_time_record, url: working_time_records_path, turboboost: true, method: :post  do |f|
  .modal.fade id="add_record" tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('working_time_records.add_record')
        .modal-body
          .row
            .col-md-6
                .form-group
                  = f.label :date, I18n.t('working_time_records.date')
                  = f.text_field :date, class: 'form-control datepicker', data: {provide: 'datepicker'}, value: Date.today
            .col-md-6
                .form-group
                  = f.label :category, I18n.t('working_time_records.category')
                  = f.select :category_id, current_user.categories.map{|c| [c.category_name, c.id]}.sort_by{|c| c[0]}, {}, {class: 'form-control'}
          .row
            .col-md-6
                .form-group
                  = f.label :start_time, t('working_time_records.start_time')
                  = f.text_field :start_time, class: 'form-control'
            .col-md-6
                .form-group
                  = f.label :end_time, I18n.t('working_time_records.end_time')
                  = f.text_field :end_time, class: 'form-control'
          
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/working_time_records/_edit_form.html.slim
= form_for working_time_record, url: working_time_record_path(working_time_record), turboboost: true, method: :patch  do |f|
  .modal.fade id="working_time_record_edit_#{working_time_record.id}" tabindex="-1" role="dialog"
    .modal-dialog role="document"
      .modal-content
        .modal-header 
          = I18n.t('working_time_records.edit_record')
        .modal-body
          .row
            .col-md-12
              .form-group
                = f.label :category_id, I18n.t('working_time_records.category')
                = f.select :category_id, current_user.categories.map{|c| [c.category_name, c.id]}.sort_by{|c| c[0]}, {}, {class: 'form-control'}
          .row
            .col-md-6
                .form-group
                  = f.label :start_time, t('working_time_records.start_time')
                  = f.text_field :start_time, class: 'form-control'
            .col-md-6
                .form-group
                  = f.label :end_time, I18n.t('working_time_records.end_time')
                  = f.text_field :end_time, class: 'form-control'
          
        .modal-footer
          button.btn.custom-btn type="submit" 
            = I18n.t('save')
          button.btn.btn-default data-dismiss="modal" 
            = I18n.t('cancel')

app/views/working_time_records/_edit_forms.html.slim
- @working_time_records.each do |working_time_record|
  = render partial: 'edit_form', locals: {working_time_record: working_time_record}

app/views/working_time_records/index.html.slim
.panel.panel-default.operation-panel
  .panel-heading
    = I18n.t('working_time_records.index')
    .btn-group.pull-right
      button.btn.btn-xs data-toggle="modal" data-target="#add_record" type="button"
        span.glyphicon.glyphicon-plus
  .panel-body 

    - r =  @working_time_records.first
    - if !r || (r && r.start_time != r.end_time)
      =button_to start_working_time_records_path, class: 'btn btn-success', method: :post
        | Start
    - else
      =button_to end_working_time_records_path, class: 'btn btn-danger', method: :post
        | End
    .row
      .col-md-6
        - diff = TimeDifference.between(Time.now, Time.now + @today_time).in_general
        p = I18n.t('working_time_records.today_work') + diff[:hours].to_s + ':' + diff[:minutes].to_s.rjust(2, '0') + ':' + diff[:seconds].to_s.rjust(2, '0')

        - week_diff = TimeDifference.between(Time.now, Time.now + @week_time).in_general
        p = I18n.t('working_time_records.week_work') + (week_diff[:hours] +  week_diff[:days] * 24).to_s + ':' + week_diff[:minutes].to_s.rjust(2, '0') + ':' + week_diff[:seconds].to_s.rjust(2, '0')

        - month_diff = TimeDifference.between(Time.now, Time.now + @month_time).in_general
        p = I18n.t('working_time_records.month_work') + ( month_diff[:weeks] * 7 * 24 + month_diff[:hours] +  month_diff[:days] * 24).to_s + ':' + month_diff[:minutes].to_s.rjust(2, '0') + ':' + month_diff[:seconds].to_s.rjust(2, '0')

      .col-md-6
        - day_to_do = TimeDifference.between(Time.now +  @today_time, Time.now + current_user.hours_number.hours).in_general
        
        - sign = ""
        - if (Time.now +  @today_time) > (Time.now + current_user.hours_number.hours)
          - sign = "-"
        
        p = I18n.t('working_time_records.today_to_work_daily') + sign + (day_to_do[:hours] + day_to_do[:days] * 24).to_s + ':' + day_to_do[:minutes].to_s.rjust(2, '0') + ':' + day_to_do[:seconds].to_s.rjust(2, '0')
        
        - minutes = (Time.now.wday > 5 ? 5 : Time.now.wday) * current_user.hours_number * 60
        - week_to_do = TimeDifference.between(Time.now +  @week_time, Time.now + minutes.minutes).in_general

        - sign = ""
        - if (Time.now + minutes.minutes) < (Time.now + @week_time)
          - sign = "-"

        p = I18n.t('working_time_records.today_to_work') + sign + (week_to_do[:hours] + week_to_do[:days] * 24).to_s + ':' + week_to_do[:minutes].to_s.rjust(2, '0') + ':' + week_to_do[:seconds].to_s.rjust(2, '0')
    
        
        p = I18n.t('working_time_records.month_salary') + ((month_diff[:weeks] * 7 * 24 + month_diff[:hours] +  month_diff[:days] * 24) * current_user.salary / current_user.hours_by_month ).round().to_s

    table.table.table-hover 
      thead
        tr
          th width="15%" = I18n.t('working_time_records.date')
          th width="30%" = I18n.t('working_time_records.category')
          th width="15%" = I18n.t('working_time_records.start_time')
          th width="15%" = I18n.t('working_time_records.end_time')
          th width="15%" = I18n.t('working_time_records.time_difference')
          th width="10%"
      tbody
       - @working_time_records.each do |r|
        tr
          td = r.start_time.strftime("%Y-%m-%d")
          td = r.category.category_name
          td = r.start_time.strftime("%H:%M")
          td = r.end_time.strftime("%H:%M")
          - d = TimeDifference.between(r.start_time, r.end_time).in_general
          td = d[:hours].to_s + ':' + d[:minutes].to_s.rjust(2, '0') + ':' + d[:seconds].to_s.rjust(2, '0')
          td
            .btn-group.pull-right
              button.btn.btn-xs.btn-primary data-toggle="modal" data-target="#working_time_record_edit_#{r.id}"
                span.glyphicon.glyphicon-pencil
              =link_to working_time_record_path(r), class: 'btn btn-xs btn-primary', method: :delete, data: {confirm: I18n.t('working_time_records.delete_confirmation_message')}
                span.glyphicon.glyphicon-remove

= render "add_record"
= render "edit_forms"
.center
  = will_paginate @working_time_records, renderer: BootstrapPagination::Rails